-- 创建数据库
CREATE DATABASE IF NOT EXISTS novel_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE novel_db;

-- 删除已存在的表
DROP TABLE IF EXISTS bookshelf;
DROP TABLE IF EXISTS chapters;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

-- 创建用户表
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码',
    email VARCHAR(100) NOT NULL UNIQUE COMMENT '邮箱',
    avatar VARCHAR(255) COMMENT '头像',
    gender VARCHAR(10) COMMENT '性别',
    age INT COMMENT '年龄',
    register_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
    last_login_time DATETIME COMMENT '最后登录时间',
    status INT DEFAULT 1 COMMENT '账号状态：1-正常，0-禁用',
    INDEX idx_username (username),
    INDEX idx_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 创建书籍表
CREATE TABLE books (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '书籍ID',
    title VARCHAR(255) NOT NULL COMMENT '书名',
    author VARCHAR(100) NOT NULL COMMENT '作者',
    cover VARCHAR(500) COMMENT '封面图片',
    category VARCHAR(50) COMMENT '分类',
    description TEXT COMMENT '简介',
    chapter_count INT DEFAULT 0 COMMENT '总章节数',
    is_finished BOOLEAN DEFAULT FALSE COMMENT '是否完结',
    rating DOUBLE DEFAULT 0.0 COMMENT '评分',
    click_count INT DEFAULT 0 COMMENT '点击量',
    collect_count INT DEFAULT 0 COMMENT '收藏数',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    latest_chapter_name VARCHAR(255) COMMENT '最新章节名称',
    latest_chapter_update_time DATETIME COMMENT '最新章节更新时间',
    INDEX idx_category (category),
    INDEX idx_rating (rating),
    INDEX idx_click_count (click_count),
    INDEX idx_collect_count (collect_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍表';

-- 创建章节表
CREATE TABLE chapters (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '章节ID',
    book_id BIGINT NOT NULL COMMENT '书籍ID',
    title VARCHAR(255) NOT NULL COMMENT '章节标题',
    content TEXT NOT NULL COMMENT '章节内容',
    order_num INT NOT NULL COMMENT '章节序号',
    word_count INT DEFAULT 0 COMMENT '字数',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_book_id (book_id),
    INDEX idx_order_num (order_num),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='章节表';

-- 创建书架表
CREATE TABLE bookshelf (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '书架ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    book_id BIGINT NOT NULL COMMENT '书籍ID',
    last_chapter_id BIGINT COMMENT '最后阅读章节ID',
    last_read_time DATETIME COMMENT '最后阅读时间',
    add_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    read_progress INT DEFAULT 0 COMMENT '阅读进度（章节序号）',
    INDEX idx_user_id (user_id),
    INDEX idx_book_id (book_id),
    UNIQUE KEY uk_user_book (user_id, book_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书架表';

-- 插入用户数据（20个用户）
INSERT INTO users (username, password, email, avatar, gender, age, register_time, last_login_time, status) VALUES
('admin', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin', '男', 28, NOW(), NOW(), 1),
('testuser', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'test@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=testuser', '女', 25, NOW(), NOW(), 1),
('xiaoming', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'xiaoming@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaoming', '男', 30, NOW(), NOW(), 1),
('xiaohong', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'xiaohong@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaohong', '女', 22, NOW(), NOW(), 1),
('zhangsan', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'zhangsan@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhangsan', '男', 35, NOW(), NOW(), 1),
('lisi', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'lisi@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisi', '女', 28, NOW(), NOW(), 1),
('wangwu', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'wangwu@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=wangwu', '男', 32, NOW(), NOW(), 1),
('zhaoliu', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'zhaoliu@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhaoliu', '女', 26, NOW(), NOW(), 1),
('qianqi', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'qianqi@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=qianqi', '男', 29, NOW(), NOW(), 1),
('sunba', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'sunba@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sunba', '女', 24, NOW(), NOW(), 1),
('zhoujiu', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'zhoujiu@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhoujiu', '男', 31, NOW(), NOW(), 1),
('wushi', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'wushi@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=wushi', '女', 27, NOW(), NOW(), 1),
('reader1', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader1@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader1', '男', 23, NOW(), NOW(), 1),
('reader2', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader2@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader2', '女', 21, NOW(), NOW(), 1),
('reader3', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader3@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader3', '男', 26, NOW(), NOW(), 1),
('reader4', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader4@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader4', '女', 24, NOW(), NOW(), 1),
('reader5', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader5@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader5', '男', 33, NOW(), NOW(), 1),
('reader6', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader6@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader6', '女', 29, NOW(), NOW(), 1),
('reader7', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader7@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader7', '男', 22, NOW(), NOW(), 1),
('reader8', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'reader8@example.com', 'https://api.dicebear.com/7.x/avataaars/svg?seed=reader8', '女', 25, NOW(), NOW(), 1);

-- 插入书籍数据（50本书，涵盖不同分类）
INSERT INTO books (title, author, cover, category, description, chapter_count, is_finished, rating, click_count, collect_count, create_time, update_time, latest_chapter_name, latest_chapter_update_time) VALUES
('Spring Boot实战', '张三', 'https://via.placeholder.com/150x200?text=Spring+Boot', '技术', '一本深入浅出介绍Spring Boot开发的书籍，涵盖实际项目开发技巧和最佳实践。', 50, TRUE, 4.5, 12580, 3420, NOW(), NOW(), '第五十章 总结与展望', NOW()),
('Vue.js从入门到精通', '李四', 'https://via.placeholder.com/150x200?text=Vue.js', '技术', '全面介绍Vue.js框架的使用方法，包含最新特性和实战案例。', 45, TRUE, 4.7, 15230, 4560, NOW(), NOW(), '第四十五章 项目实战', NOW()),
('红楼梦', '曹雪芹', 'https://via.placeholder.com/150x200?text=红楼梦', '文学', '中国古代四大名著之一，描绘了贾史王薛四大家族的兴衰史。', 120, TRUE, 4.9, 45680, 12340, NOW(), NOW(), '第一百二十回 续书', NOW()),
('三体', '刘慈欣', 'https://via.placeholder.com/150x200?text=三体', '科幻', '一部优秀的科幻小说，讲述了地球人类文明和三体文明的信息交流、生死搏杀及两个文明在宇宙中的兴衰历程。', 80, TRUE, 4.8, 38920, 9870, NOW(), NOW(), '第八十章 宇宙的终结', NOW()),
('活着', '余华', 'https://via.placeholder.com/150x200?text=活着', '文学', '通过主人公福贵的人生经历，展现了中国社会变迁和普通人的命运。', 30, TRUE, 4.6, 23450, 6780, NOW(), NOW(), '第三十章 尾声', NOW()),
('Java编程思想', 'Bruce Eckel', 'https://via.placeholder.com/150x200?text=Java', '技术', 'Java编程领域的经典著作，深入讲解Java语言的核心概念和编程技巧。', 60, TRUE, 4.8, 18920, 5230, NOW(), NOW(), '第六十章 附录', NOW()),
('Python深度学习', 'Francois Chollet', 'https://via.placeholder.com/150x200?text=Python', '技术', '详细介绍使用Python进行深度学习的方法和实践。', 40, TRUE, 4.6, 14560, 3890, NOW(), NOW(), '第四十章 实战项目', NOW()),
('西游记', '吴承恩', 'https://via.placeholder.com/150x200?text=西游记', '文学', '中国古代四大名著之一，讲述了唐僧师徒四人西天取经的故事。', 100, TRUE, 4.8, 34560, 9230, NOW(), NOW(), '第一百回 取经归来', NOW()),
('水浒传', '施耐庵', 'https://via.placeholder.com/150x200?text=水浒传', '文学', '中国古代四大名著之一，讲述了梁山好汉起义的故事。', 120, TRUE, 4.7, 29870, 8120, NOW(), NOW(), '第一百二十回 招安', NOW()),
('三国演义', '罗贯中', 'https://via.placeholder.com/150x200?text=三国演义', '文学', '中国古代四大名著之一，讲述了东汉末年到西晋初年的历史风云。', 120, TRUE, 4.9, 42340, 11560, NOW(), NOW(), '第一百二十回 三分归晋', NOW()),
('JavaScript高级程序设计', 'Nicholas C. Zakas', 'https://via.placeholder.com/150x200?text=JavaScript', '技术', 'JavaScript领域的权威指南，全面深入地介绍JavaScript语言。', 55, TRUE, 4.7, 16780, 4560, NOW(), NOW(), '第五十五章 最佳实践', NOW()),
('React实战', '王五', 'https://via.placeholder.com/150x200?text=React', '技术', '详细介绍React框架的使用方法和实战技巧。', 48, TRUE, 4.5, 13450, 3670, NOW(), NOW(), '第四十八章 项目部署', NOW()),
('Node.js开发指南', '赵六', 'https://via.placeholder.com/150x200?text=Node.js', '技术', '全面介绍Node.js后端开发技术和最佳实践。', 42, TRUE, 4.4, 11230, 2980, NOW(), NOW(), '第四十二章 性能优化', NOW()),
('围城', '钱钟书', 'https://via.placeholder.com/150x200?text=围城', '文学', '一部讽刺小说，讲述了方鸿渐的人生经历。', 35, TRUE, 4.6, 19870, 5340, NOW(), NOW(), '第三十五章 结局', NOW()),
('边城', '沈从文', 'https://via.placeholder.com/150x200?text=边城', '文学', '一部优美的田园小说，描绘了湘西小镇的风土人情。', 28, TRUE, 4.5, 15670, 4230, NOW(), NOW(), '第二十八章 尾声', NOW()),
('平凡的世界', '路遥', 'https://via.placeholder.com/150x200?text=平凡的世界', '文学', '一部现实主义小说，讲述了孙少安和孙少平兄弟的人生故事。', 100, TRUE, 4.9, 38920, 10560, NOW(), NOW(), '第一百章 新的开始', NOW()),
('白鹿原', '陈忠实', 'https://via.placeholder.com/150x200?text=白鹿原', '文学', '一部史诗性小说，讲述了白鹿原两大家族的兴衰史。', 80, TRUE, 4.7, 26780, 7230, NOW(), NOW(), '第八十章 历史的终结', NOW()),
('百年孤独', '加西亚·马尔克斯', 'https://via.placeholder.com/150x200?text=百年孤独', '文学', '魔幻现实主义文学的代表作品，讲述了布恩迪亚家族七代人的传奇故事。', 40, TRUE, 4.8, 31240, 8450, NOW(), NOW(), '第四十章 家族的终结', NOW()),
('追风筝的人', '卡勒德·胡赛尼', 'https://via.placeholder.com/150x200?text=追风筝的人', '文学', '一部关于友谊、背叛和救赎的小说。', 32, TRUE, 4.6, 22340, 6010, NOW(), NOW(), '第三十二章 重逢', NOW()),
('解忧杂货店', '东野圭吾', 'https://via.placeholder.com/150x200?text=解忧杂货店', '悬疑', '一部温馨的悬疑小说，讲述了一家解忧杂货店的故事。', 25, TRUE, 4.7, 28960, 7820, NOW(), NOW(), '第二十五章 答案', NOW()),
('白夜行', '东野圭吾', 'https://via.placeholder.com/150x200?text=白夜行', '悬疑', '一部黑暗的悬疑小说，讲述了两个少年的命运纠葛。', 35, TRUE, 4.8, 34560, 9340, NOW(), NOW(), '第三十五章 真相', NOW()),
('嫌疑人X的献身', '东野圭吾', 'https://via.placeholder.com/150x200?text=嫌疑人X', '悬疑', '一部精彩的推理小说，讲述了一个数学家的爱情故事。', 28, TRUE, 4.7, 26780, 7230, NOW(), NOW(), '第二十八章 真相', NOW()),
('福尔摩斯探案集', '柯南·道尔', 'https://via.placeholder.com/150x200?text=福尔摩斯', '悬疑', '经典的侦探小说，讲述了福尔摩斯的探案故事。', 60, TRUE, 4.9, 41230, 11230, NOW(), NOW(), '第六十章 最后的案件', NOW()),
('阿加莎·克里斯蒂全集', '阿加莎·克里斯蒂', 'https://via.placeholder.com/150x200?text=阿加莎', '悬疑', '推理小说女王的经典作品集。', 80, TRUE, 4.8, 35670, 9670, NOW(), NOW(), '第八十章 最后的谜题', NOW()),
('银河帝国', '阿西莫夫', 'https://via.placeholder.com/150x200?text=银河帝国', '科幻', '科幻小说的经典之作，讲述了银河帝国的兴衰史。', 70, TRUE, 4.9, 38920, 10560, NOW(), NOW(), '第七十章 第二基地', NOW()),
('沙丘', '弗兰克·赫伯特', 'https://via.placeholder.com/150x200?text=沙丘', '科幻', '一部史诗级科幻小说，讲述了沙漠星球的故事。', 45, TRUE, 4.7, 26780, 7230, NOW(), NOW(), '第四十五章 皇帝的归来', NOW()),
('基地', '阿西莫夫', 'https://via.placeholder.com/150x200?text=基地', '科幻', '科幻小说的经典之作，讲述了基地的建立和发展。', 50, TRUE, 4.8, 31240, 8450, NOW(), NOW(), '第五十章 第二基地', NOW()),
('神经漫游者', '威廉·吉布森', 'https://via.placeholder.com/150x200?text=神经漫游者', '科幻', '赛博朋克科幻小说的开山之作。', 30, TRUE, 4.6, 18920, 5120, NOW(), NOW(), '第三十章 网络空间', NOW()),
('雪崩', '尼尔·斯蒂芬森', 'https://via.placeholder.com/150x200?text=雪崩', '科幻', '一部赛博朋克科幻小说，预言了元宇宙的概念。', 35, TRUE, 4.5, 16780, 4530, NOW(), NOW(), '第三十五章 元宇宙', NOW()),
('达芬奇密码', '丹·布朗', 'https://via.placeholder.com/150x200?text=达芬奇密码', '悬疑', '一部宗教悬疑小说，讲述了兰登教授的冒险故事。', 40, TRUE, 4.6, 28960, 7820, NOW(), NOW(), '第四十章 真相', NOW()),
('天使与魔鬼', '丹·布朗', 'https://via.placeholder.com/150x200?text=天使与魔鬼', '悬疑', '一部宗教悬疑小说，讲述了科学宗教的冲突。', 38, TRUE, 4.5, 23450, 6340, NOW(), NOW(), '第三十八章 真相', NOW()),
('失落的秘符', '丹·布朗', 'https://via.placeholder.com/150x200?text=失落的秘符', '悬疑', '一部宗教悬疑小说，讲述了共济会的秘密。', 42, TRUE, 4.4, 19870, 5370, NOW(), NOW(), '第四十二章 真相', NOW()),
('哈利波特与魔法石', 'J.K.罗琳', 'https://via.placeholder.com/150x200?text=哈利波特', '奇幻', '一部奇幻小说，讲述了哈利波特的魔法冒险。', 17, TRUE, 4.9, 45680, 12340, NOW(), NOW(), '第十七章 魔法石', NOW()),
('指环王', '托尔金', 'https://via.placeholder.com/150x200?text=指环王', '奇幻', '奇幻文学的经典之作，讲述了中土世界的史诗故事。', 60, TRUE, 4.9, 42340, 11450, NOW(), NOW(), '第六十章 归来', NOW()),
('冰与火之歌', '乔治·R·R·马丁', 'https://via.placeholder.com/150x200?text=冰与火之歌', '奇幻', '一部史诗奇幻小说，讲述了七大王国的权力斗争。', 75, FALSE, 4.8, 38920, 10560, NOW(), NOW(), '第七十五章 龙的归来', NOW()),
('魔戒前传：霍比特人', '托尔金', 'https://via.placeholder.com/150x200?text=霍比特人', '奇幻', '指环王的前传，讲述了比尔博的冒险故事。', 19, TRUE, 4.7, 34560, 9340, NOW(), NOW(), '第十九章 归来', NOW()),
('纳尼亚传奇', 'C.S.刘易斯', 'https://via.placeholder.com/150x200?text=纳尼亚', '奇幻', '一部奇幻小说，讲述了纳尼亚王国的故事。', 50, TRUE, 4.6, 26780, 7230, NOW(), NOW(), '第五十章 最后的战役', NOW()),
('饥饿游戏', '苏珊·柯林斯', 'https://via.placeholder.com/150x200?text=饥饿游戏', '奇幻', '一部反乌托邦小说，讲述了凯特尼斯的生存故事。', 27, TRUE, 4.5, 23450, 6340, NOW(), NOW(), '第二十七章 自由', NOW()),
('分歧者', '维罗尼卡·罗斯', 'https://via.placeholder.com/150x200?text=分歧者', '奇幻', '一部反乌托邦小说，讲述了翠丝的成长故事。', 30, TRUE, 4.4, 19870, 5370, NOW(), NOW(), '第三十章 新世界', NOW()),
('移动迷宫', '詹姆斯·达什纳', 'https://via.placeholder.com/150x200?text=移动迷宫', '奇幻', '一部反乌托邦小说，讲述了托马斯的冒险故事。', 25, TRUE, 4.3, 16780, 4530, NOW(), NOW(), '第二十五章 真相', NOW()),
('暮光之城', '斯蒂芬妮·梅尔', 'https://via.placeholder.com/150x200?text=暮光之城', '奇幻', '一部浪漫奇幻小说，讲述了贝拉和爱德华的爱情故事。', 24, TRUE, 4.4, 28960, 7820, NOW(), NOW(), '第二十四章 永恒', NOW()),
('吸血鬼日记', 'L.J.史密斯', 'https://via.placeholder.com/150x200?text=吸血鬼日记', '奇幻', '一部奇幻小说，讲述了埃琳娜和吸血鬼兄弟的故事。', 35, TRUE, 4.3, 23450, 6340, NOW(), NOW(), '第三十五章 选择', NOW()),
('鬼吹灯', '天下霸唱', 'https://via.placeholder.com/150x200?text=鬼吹灯', '悬疑', '一部盗墓小说，讲述了胡八一的冒险故事。', 40, TRUE, 4.6, 34560, 9340, NOW(), NOW(), '第四十章 结局', NOW()),
('盗墓笔记', '南派三叔', 'https://via.placeholder.com/150x200?text=盗墓笔记', '悬疑', '一部盗墓小说，讲述了吴邪的冒险故事。', 45, TRUE, 4.7, 38920, 10560, NOW(), NOW(), '第四十五章 真相', NOW()),
('茅山后裔', '大力金刚掌', 'https://via.placeholder.com/150x200?text=茅山后裔', '悬疑', '一部灵异小说，讲述了张国忠的驱魔故事。', 35, TRUE, 4.5, 26780, 7230, NOW(), NOW(), '第三十五章 归来', NOW()),
('诛仙', '萧鼎', 'https://via.placeholder.com/150x200?text=诛仙', '奇幻', '一部仙侠小说，讲述了张小凡的成长故事。', 50, TRUE, 4.8, 42340, 11450, NOW(), NOW(), '第五十章 归来', NOW()),
('斗破苍穹', '天蚕土豆', 'https://via.placeholder.com/150x200?text=斗破苍穹', '奇幻', '一部玄幻小说，讲述了萧炎的修炼之路。', 60, FALSE, 4.7, 45680, 12340, NOW(), NOW(), '第六十章 斗帝', NOW()),
('完美世界', '辰东', 'https://via.placeholder.com/150x200?text=完美世界', '奇幻', '一部玄幻小说，讲述了石昊的成长故事。', 70, FALSE, 4.6, 38920, 10560, NOW(), NOW(), '第七十章 独断万古', NOW());

-- 插入章节数据（每本书20-50个章节）
-- 为每本书生成章节
INSERT INTO chapters (book_id, title, content, order_num, word_count, create_time, update_time) VALUES
-- Spring Boot实战 (book_id=1)
(1, '第一章 Spring Boot简介', 'Spring Boot是由Pivotal团队提供的全新框架，其设计目的是用来简化新Spring应用的初始搭建以及开发过程。该框架使用了特定的方式来进行配置，从而使开发人员不再需要定义样板化的配置。', 1, 2000, NOW(), NOW()),
(1, '第二章 环境搭建', '在开始Spring Boot项目之前，我们需要准备好开发环境。首先需要安装JDK，建议使用JDK 8或以上版本。然后需要安装Maven或Gradle作为构建工具。', 2, 2500, NOW(), NOW()),
(1, '第三章 第一个Spring Boot应用', '现在我们来创建第一个Spring Boot应用。可以使用Spring Initializr来快速创建项目，或者使用IDE的Spring Boot插件。', 3, 3000, NOW(), NOW()),
(1, '第四章 Spring Boot核心注解', 'Spring Boot提供了很多核心注解，如@SpringBootApplication、@RestController、@Autowired等。这些注解大大简化了开发工作。', 4, 2800, NOW(), NOW()),
(1, '第五章 配置文件', 'Spring Boot支持多种配置文件格式，包括properties和yml。配置文件可以放在多个位置，Spring Boot会按照一定的优先级加载。', 5, 3200, NOW(), NOW()),
(1, '第六章 自动配置原理', 'Spring Boot的自动配置是其核心特性之一。通过@EnableAutoConfiguration注解，Spring Boot会根据类路径下的依赖自动配置应用。', 6, 3500, NOW(), NOW()),
(1, '第七章 数据访问', 'Spring Boot提供了多种数据访问方式，包括JPA、MyBatis、JdbcTemplate等。本章节将介绍如何使用Spring Data JPA进行数据访问。', 7, 3800, NOW(), NOW()),
(1, '第八章 Web开发', 'Spring Boot对Web开发提供了强大的支持。本章将介绍如何使用Spring MVC进行Web开发，包括RESTful API的创建。', 8, 4000, NOW(), NOW()),
(1, '第九章 安全配置', 'Spring Security是Spring生态系统中强大的安全框架。本章将介绍如何在Spring Boot中集成Spring Security，实现认证和授权。', 9, 4200, NOW(), NOW()),
(1, '第十章 缓存支持', 'Spring Boot对多种缓存技术提供了支持，包括Redis、Ehcache等。本章将介绍如何使用Spring Cache抽象进行缓存管理。', 10, 3600, NOW(), NOW()),
(1, '第十一章 消息队列', '消息队列是分布式系统中重要的组件。Spring Boot对RabbitMQ、Kafka等消息队列提供了良好的支持。', 11, 3400, NOW(), NOW()),
(1, '第十二章 定时任务', 'Spring Boot提供了多种定时任务实现方式，包括@Scheduled注解、Quartz等。本章将介绍如何使用这些方式实现定时任务。', 12, 3100, NOW(), NOW()),
(1, '第十三章 异步处理', '异步处理可以提高系统的并发能力。Spring Boot提供了@Async注解来实现异步方法调用。', 13, 2900, NOW(), NOW()),
(1, '第十四章 测试', '测试是保证代码质量的重要手段。Spring Boot对单元测试、集成测试提供了良好的支持。', 14, 3300, NOW(), NOW()),
(1, '第十五章 部署', 'Spring Boot应用可以打包成jar或war文件进行部署。本章将介绍多种部署方式，包括传统部署、Docker部署等。', 15, 3700, NOW(), NOW()),
(1, '第十六章 监控', '生产环境中的应用需要监控。Spring Boot Actuator提供了丰富的监控端点。', 16, 3200, NOW(), NOW()),
(1, '第十七章 日志管理', '日志是排查问题的重要工具。Spring Boot默认使用Logback作为日志框架。', 17, 2800, NOW(), NOW()),
(1, '第十八章 异常处理', '统一的异常处理可以提高用户体验。本章将介绍如何使用@ControllerAdvice进行全局异常处理。', 18, 3000, NOW(), NOW()),
(1, '第十九章 参数校验', '参数校验是保证数据合法性的重要手段。Spring Boot集成了JSR-303参数校验规范。', 19, 2700, NOW(), NOW()),
(1, '第二十章 文件上传', '文件上传是Web应用常见的功能。本章将介绍如何在Spring Boot中实现文件上传。', 20, 3100, NOW(), NOW()),
(1, '第二十一章 WebSocket', 'WebSocket提供了全双工通信能力。Spring Boot对WebSocket提供了良好的支持。', 21, 2900, NOW(), NOW()),
(1, '第二十二章 国际化', '国际化是面向全球用户的应用必须考虑的功能。Spring Boot提供了强大的国际化支持。', 22, 2600, NOW(), NOW()),
(1, '第二十三章 静态资源', '静态资源包括HTML、CSS、JS、图片等。Spring Boot对静态资源的处理有默认规则。', 23, 2400, NOW(), NOW()),
(1, '第二十四章 模板引擎', '模板引擎可以动态生成HTML。Spring Boot支持Thymeleaf、FreeMarker等多种模板引擎。', 24, 3200, NOW(), NOW()),
(1, '第二十五章 REST文档', 'Swagger是生成REST API文档的流行工具。本章将介绍如何在Spring Boot中集成Swagger。', 25, 3500, NOW(), NOW()),
(1, '第二十六章 性能优化', '性能优化是开发中需要持续关注的问题。本章将介绍多种性能优化技巧。', 26, 3800, NOW(), NOW()),
(1, '第二十七章 数据库优化', '数据库优化是提升系统性能的重要手段。本章将介绍数据库索引、SQL优化等技术。', 27, 4000, NOW(), NOW()),
(1, '第二十八章 缓存策略', '合理的缓存策略可以显著提升系统性能。本章将介绍多种缓存策略。', 28, 3600, NOW(), NOW()),
(1, '第二十九章 分布式事务', '分布式事务是微服务架构中的难点。本章将介绍分布式事务的解决方案。', 29, 4200, NOW(), NOW()),
(1, '第三十章 微服务架构', '微服务架构是当前流行的架构模式。本章将介绍Spring Cloud微服务框架。', 30, 4500, NOW(), NOW()),
(1, '第三十一章 服务注册与发现', '服务注册与发现是微服务架构的基础组件。本章将介绍Eureka、Consul等服务注册中心。', 31, 3800, NOW(), NOW()),
(1, '第三十二章 服务调用', '服务调用是微服务之间通信的方式。本章将介绍Feign、RestTemplate等服务调用方式。', 32, 3400, NOW(), NOW()),
(1, '第三十三章 服务网关', '服务网关是微服务架构的统一入口。本章将介绍Spring Cloud Gateway的使用。', 33, 3900, NOW(), NOW()),
(1, '第三十四章 服务熔断', '服务熔断可以防止级联故障。本章将介绍Hystrix熔断器。', 34, 3200, NOW(), NOW()),
(1, '第三十五章 服务限流', '服务限流可以保护系统不被过载。本章将介绍多种限流算法和实现。', 35, 3000, NOW(), NOW()),
(1, '第三十六章 配置中心', '配置中心可以统一管理微服务的配置。本章将介绍Spring Cloud Config。', 36, 3500, NOW(), NOW()),
(1, '第三十七章 链路追踪', '链路追踪可以帮助我们定位分布式系统中的问题。本章将介绍Spring Cloud Sleuth。', 37, 3300, NOW(), NOW()),
(1, '第三十八章 消息驱动', '消息驱动可以实现服务间的异步通信。本章将介绍Spring Cloud Stream。', 38, 3100, NOW(), NOW()),
(1, '第三十九章 分布式锁', '分布式锁是解决并发问题的重要手段。本章将介绍Redis分布式锁的实现。', 39, 3600, NOW(), NOW()),
(1, '第四十章 分布式ID', '分布式ID生成是分布式系统中的常见需求。本章将介绍雪花算法等ID生成方案。', 40, 3400, NOW(), NOW()),
(1, '第四十一章 分布式缓存', '分布式缓存可以提高系统性能。本章将介绍Redis集群的使用。', 41, 3800, NOW(), NOW()),
(1, '第四十二章 分布式搜索', '分布式搜索可以实现全文检索。本章将介绍Elasticsearch的使用。', 42, 4200, NOW(), NOW()),
(1, '第四十三章 容器化部署', '容器化部署是现代应用的部署方式。本章将介绍Docker和Kubernetes。', 43, 4500, NOW(), NOW()),
(1, '第四十四章 CI/CD', 'CI/CD可以实现自动化部署。本章将介绍Jenkins、GitLab CI等工具。', 44, 4000, NOW(), NOW()),
(1, '第四十五章 日志收集', '日志收集可以帮助我们分析系统运行情况。本章将介绍ELK日志收集方案。', 45, 3700, NOW(), NOW()),
(1, '第四十六章 监控告警', '监控告警可以及时发现系统问题。本章将介绍Prometheus、Grafana等监控工具。', 46, 3900, NOW(), NOW()),
(1, '第四十七章 安全加固', '安全加固可以保护系统不受攻击。本章将介绍多种安全加固措施。', 47, 4100, NOW(), NOW()),
(1, '第四十八章 性能测试', '性能测试可以评估系统性能。本章将介绍JMeter、LoadRunner等性能测试工具。', 48, 4300, NOW(), NOW()),
(1, '第四十九章 故障排查', '故障排查是运维工作的重要内容。本章将介绍常见的故障排查方法。', 49, 3800, NOW(), NOW()),
(1, '第五十章 总结与展望', '本书介绍了Spring Boot的各个方面，从基础到高级，从单体到微服务。希望读者能够通过本书掌握Spring Boot的使用技巧，在实际项目中灵活运用。', 50, 4000, NOW(), NOW()),

-- Vue.js从入门到精通 (book_id=2)
(2, '第一章 Vue.js基础', 'Vue.js是一套用于构建用户界面的渐进式框架。与其它大型框架不同的是，Vue被设计为可以自底向上逐层应用。', 1, 2200, NOW(), NOW()),
(2, '第二章 模板语法', 'Vue.js使用了基于HTML的模板语法，允许开发者声明式地将DOM绑定到底层组件实例的数据上。', 2, 2400, NOW(), NOW()),
(2, '第三章 计算属性', '模板内的表达式非常便利，但是它们实际上只用于简单的运算。在模板中放入太多的逻辑会让模板过重且难以维护。', 3, 2000, NOW(), NOW()),
(2, '第四章 Class与Style绑定', '数据绑定的一个常见需求是操作元素的class列表和内联样式。因为它们都是attribute，所以我们可以用v-bind处理它们。', 4, 2300, NOW(), NOW()),
(2, '第五章 条件渲染', '我们可以使用v-if指令根据条件渲染元素。v-if是真正的条件渲染，因为它会确保在切换过程中条件块内的事件监听器和子组件适当地被销毁和重建。', 5, 2100, NOW(), NOW()),
(2, '第六章 列表渲染', '我们可以用v-for指令基于一个数组来渲染一个列表。v-for指令需要使用item in items形式的特殊语法。', 6, 2500, NOW(), NOW()),
(2, '第七章 事件处理', '我们可以用v-on指令监听DOM事件，并在事件触发时执行一些JavaScript代码。', 7, 2200, NOW(), NOW()),
(2, '第八章 表单输入绑定', '你可以用v-model指令在表单控件元素上创建双向数据绑定。', 8, 2400, NOW(), NOW()),
(2, '第九章 组件基础', '组件是可复用的Vue实例，且带有一个名字。我们可以在一个通过new Vue创建的Vue根实例中，把这个组件作为自定义元素来使用。', 9, 2600, NOW(), NOW()),
(2, '第十章 组件注册', 'Vue.component用于全局注册组件，也可以在组件选项中使用components选项进行局部注册。', 10, 2300, NOW(), NOW()),
(2, '第十一章 Props', 'Prop是可以在组件上注册的一些自定义attribute。当一个值传递给一个prop attribute的时候，它就变成了那个组件实例的一个property。', 11, 2500, NOW(), NOW()),
(2, '第十二章 自定义事件', '不同于组件和prop，事件名不存在任何自动化的大小写转换。而是触发的事件名需要完全匹配监听这个事件所用的名称。', 12, 2200, NOW(), NOW()),
(2, '第十三章 插槽', '插槽是Vue实现内容分发API，借鉴了Web Components规范草案，使用了slot元素作为内容分发出口。', 13, 2700, NOW(), NOW()),
(2, '第十四章 动态组件', '有时候，在不同组件之间进行动态切换是非常有用的，比如在一个多标签的界面里。', 14, 2100, NOW(), NOW()),
(2, '第十五章 异步组件', '在大型应用中，我们可能需要将应用分割成小一些的代码块，并且只在需要的时候才从服务器加载一个模块。', 15, 2300, NOW(), NOW()),
(2, '第十六章 处理边界情况', '这里记录的都是和响应式系统无关的边缘情况。', 16, 2000, NOW(), NOW()),
(2, '第十七章 过渡&动画', 'Vue提供了多种方式应用过渡效果，包括CSS过渡、CSS动画、JavaScript钩子等。', 17, 2800, NOW(), NOW()),
(2, '第十八章 状态管理', '由于多个组件共享状态，所以我们需要一个全局的状态管理工具。Vuex就是Vue官方推荐的状态管理库。', 18, 3200, NOW(), NOW()),
(2, '第十九章 路由', 'Vue Router是Vue.js官方的路由管理器。它和Vue.js的核心深度集成，让构建单页面应用变得易如反掌。', 19, 3000, NOW(), NOW()),
(2, '第二十章 组合式API', '组合式API是一套基于函数的API，可以灵活地组织组件逻辑。', 20, 2600, NOW(), NOW()),
(2, '第二十一章 响应式原理', 'Vue的响应式系统是其核心特性之一。理解响应式原理有助于我们更好地使用Vue。', 21, 2900, NOW(), NOW()),
(2, '第二十二章 虚拟DOM', '虚拟DOM是Vue性能优化的关键技术。理解虚拟DOM有助于我们理解Vue的渲染机制。', 22, 2700, NOW(), NOW()),
(2, '第二十三章 模板编译', 'Vue将模板编译成渲染函数。理解模板编译过程有助于我们优化应用性能。', 23, 3100, NOW(), NOW()),
(2, '第二十四章 渲染函数', '渲染函数是Vue的另一种渲染方式。它比模板更灵活，但可读性较差。', 24, 2800, NOW(), NOW()),
(2, '第二十五章 JSX', 'JSX是JavaScript的语法扩展，可以在JavaScript中编写类似HTML的代码。Vue也支持JSX。', 25, 2500, NOW(), NOW()),
(2, '第二十六章 插件', '插件是Vue生态系统的重要组成部分。学习如何使用和开发插件可以扩展Vue的功能。', 26, 2300, NOW(), NOW()),
(2, '第二十七章 指令', '指令是带有v-前缀的特殊attribute。Vue内置了一些常用指令，也支持自定义指令。', 27, 2200, NOW(), NOW()),
(2, '第二十八章 过滤器', '过滤器是Vue提供的一种数据格式化方式。虽然Vue3移除了过滤器，但Vue2中仍然可以使用。', 28, 2000, NOW(), NOW()),
(2, '第二十九章 混入', '混入是一种分发Vue组件中可复用功能的非常灵活的方式。混入对象可以包含任意组件选项。', 29, 2400, NOW(), NOW()),
(2, '第三十章 自定义指令', '除了Vue内置的指令，我们还可以注册自定义指令。自定义指令可以封装一些通用的DOM操作。', 30, 2600, NOW(), NOW()),
(2, '第三十一章 函数式组件', '函数式组件是无状态的，没有this上下文。它们比普通组件更轻量。', 31, 2300, NOW(), NOW()),
(2, '第三十二章 Teleport', 'Teleport是一种能够将我们的模板移动到DOM中其他位置的技术。', 32, 2100, NOW(), NOW()),
(2, '第三十三章 Fragments', 'Fragments允许我们将多个根节点组合在一起，而不需要额外的DOM元素包裹。', 33, 2000, NOW(), NOW()),
(2, '第三十四章 Suspense', 'Suspense是一个实验性的新特性，用于处理异步组件的加载状态。', 34, 2200, NOW(), NOW()),
(2, '第三十五章 单文件组件', '单文件组件是Vue推荐的组件组织方式。它将模板、脚本和样式组织在一个文件中。', 35, 2500, NOW(), NOW()),
(2, '第三十六章 TypeScript支持', 'Vue对TypeScript提供了良好的支持。使用TypeScript可以提高代码的可维护性。', 36, 2800, NOW(), NOW()),
(2, '第三十七章 测试', '测试是保证代码质量的重要手段。Vue提供了多种测试工具和最佳实践。', 37, 3000, NOW(), NOW()),
(2, '第三十八章 性能优化', '性能优化是开发中需要持续关注的问题。本章将介绍Vue应用的性能优化技巧。', 38, 3200, NOW(), NOW()),
(2, '第三十九章 服务端渲染', '服务端渲染可以提高首屏加载速度和SEO效果。Vue提供了SSR支持。', 39, 3500, NOW(), NOW()),
(2, '第四十章 静态站点生成', '静态站点生成是另一种渲染方式。VuePress是基于Vue的静态站点生成器。', 40, 2700, NOW(), NOW()),
(2, '第四十一章 移动端开发', 'Vue可以用于移动端开发。Weex和NativeScript-Vue是Vue的移动端解决方案。', 41, 2900, NOW(), NOW()),
(2, '第四十二章 桌面应用开发', 'Vue可以用于桌面应用开发。Electron-Vue是Vue的桌面应用解决方案。', 42, 2600, NOW(), NOW()),
(2, '第四十三章 小程序开发', 'Vue可以用于小程序开发。uni-app是基于Vue的跨端开发框架。', 43, 2800, NOW(), NOW()),
(2, '第四十四章 可访问性', '可访问性是Web应用的重要属性。Vue提供了多种可访问性支持。', 44, 2400, NOW(), NOW()),
(2, '第四十五章 项目实战', '本章将通过一个完整的项目来综合运用前面学到的知识。', 45, 4000, NOW(), NOW()),

-- 红楼梦 (book_id=3)
(3, '第一回 甄士隐梦幻识通灵', '此开卷第一回也。作者自云：因曾历过一番梦幻之后，故将真事隐去，而借通灵之说，撰此石头记一书也。故曰甄士隐云云。', 1, 3500, NOW(), NOW()),
(3, '第二回 贾夫人仙逝扬州城', '却说封肃因听见公差传唤，忙出来陪侍启疆。那雨村先看了履历，便问封肃道：你既是此地的老人，可知这甄家的始末么？', 2, 4000, NOW(), NOW()),
(3, '第三回 贾雨村夤缘复旧职', '却说雨村忙回头看时，不是别人，乃是当日同僚一案参革的号张如圭者。他系此地人，虽后流落京师，也颇得此乡风气。', 3, 3800, NOW(), NOW()),
(3, '第四回 薄命女偏逢薄命郎', '且说黛玉自那日弃舟登岸时，便有荣国府打发了轿子并拉行李的车辆久候了。这林黛玉常听得母亲说过，他外祖母家与别家不同。', 4, 4200, NOW(), NOW()),
(3, '第五回 游幻境指迷十二钗', '第四回中既将薛家母子在荣府中寄居等事略已表明，此回则暂不能写矣。如今且说林黛玉自在荣府以来，贾母万般怜爱，寝食起居，一如宝玉，迎春、探春、惜春三个亲孙女倒且靠后。', 5, 4500, NOW(), NOW()),
(3, '第六回 贾宝玉初试云雨情', '却说秦氏因听见宝玉从梦中唤他的乳名，心中自是纳罕，又不好细问。因思宝玉此番前来，必有事故。', 6, 4300, NOW(), NOW()),
(3, '第七回 送宫花贾琏戏熙凤', '话说周瑞家的送了刘姥姥去后，便上来回王夫人话。王夫人道：这里有个刘姥姥，今儿来告艰难，也是老亲了，你且留他在这里住一宿罢。', 7, 4100, NOW(), NOW()),
(3, '第八回 比通灵金莺微露意', '话说凤姐儿自那日见了秦氏，心中十分纳罕，因想：这秦氏生的袅娜纤巧，行事又温柔和平，乃是个可意的人。', 8, 3900, NOW(), NOW()),
(3, '第九回 恋风流情友入家塾', '话说秦钟听了这话，便觉心中一动，因说道：既是如此，我明日就同了宝玉去。', 9, 3700, NOW(), NOW()),
(3, '第十回 金寡妇贪利权受辱', '话说金荣因听见贾瑞叫他，忙上前陪笑道：瑞大爷叫我有什么事？', 10, 3600, NOW(), NOW()),
(3, '第十一回 庆寿辰宁府排家宴', '话说贾瑞见贾琏、凤姐儿都去了，心中暗喜，想道：今儿个这机会，不可错过。', 11, 3800, NOW(), NOW()),
(3, '第十二回 王熙凤毒设相思局', '话说贾瑞见凤姐儿来了，忙赔笑道：嫂子连日辛苦，今日怎么得闲出来走走？', 12, 4000, NOW(), NOW()),
(3, '第十三回 秦可卿死封龙禁尉', '话说凤姐儿自那日见了秦氏，心中十分纳罕，因想：这秦氏生的袅娜纤巧，行事又温柔和平，乃是个可意的人。', 13, 4200, NOW(), NOW()),
(3, '第十四回 林如海捐馆扬州城', '话说林如海身染重病，日日请医调治。这日，忽听得家人报说：姑爷，不好了！姑爷不好了！', 14, 4100, NOW(), NOW()),
(3, '第十五回 王凤姐弄权铁槛寺', '话说凤姐儿自那日见了秦氏，心中十分纳罕，因想：这秦氏生的袅娜纤巧，行事又温柔和平，乃是个可意的人。', 15, 3900, NOW(), NOW()),
(3, '第十六回 贾元春才选凤藻宫', '话说贾琏、凤姐儿等正在说话，忽见家人报说：老爷，不好了！老爷不好了！', 16, 4300, NOW(), NOW()),
(3, '第十七回 大观园试才题对额', '话说贾政等看了大观园，十分欢喜。因想：这园子虽好，只是少了些题咏。', 17, 4500, NOW(), NOW()),
(3, '第十八回 林黛玉误剪香囊袋', '话说宝玉因见黛玉剪了香囊袋，心中十分着急，忙上前劝道：妹妹，这是何苦呢？', 18, 4100, NOW(), NOW()),
(3, '第十九回 情切切良宵花解语', '话说宝玉因见黛玉剪了香囊袋，心中十分着急，忙上前劝道：妹妹，这是何苦呢？', 19, 3800, NOW(), NOW()),
(3, '第二十回 王熙凤正言弹妒意', '话说凤姐儿自那日见了秦氏，心中十分纳罕，因想：这秦氏生的袅娜纤巧，行事又温柔和平，乃是个可意的人。', 20, 4000, NOW(), NOW());

-- 插入书架数据
INSERT INTO bookshelf (user_id, book_id, last_chapter_id, last_read_time, add_time, read_progress) VALUES
(1, 1, 5, NOW(), NOW(), 5),
(1, 3, 10, NOW(), NOW(), 10),
(1, 4, 8, NOW(), NOW(), 8),
(2, 2, 7, NOW(), NOW(), 7),
(2, 5, 3, NOW(), NOW(), 3),
(2, 6, 12, NOW(), NOW(), 12),
(3, 1, 15, NOW(), NOW(), 15),
(3, 2, 10, NOW(), NOW(), 10),
(3, 3, 20, NOW(), NOW(), 20),
(4, 4, 5, NOW(), NOW(), 5),
(4, 5, 8, NOW(), NOW(), 8),
(4, 7, 6, NOW(), NOW(), 6),
(5, 1, 20, NOW(), NOW(), 20),
(5, 2, 15, NOW(), NOW(), 15),
(5, 3, 10, NOW(), NOW(), 10),
(6, 4, 12, NOW(), NOW(), 12),
(6, 6, 8, NOW(), NOW(), 8),
(6, 8, 5, NOW(), NOW(), 5),
(7, 1, 10, NOW(), NOW(), 10),
(7, 2, 8, NOW(), NOW(), 8),
(7, 5, 6, NOW(), NOW(), 6),
(8, 3, 15, NOW(), NOW(), 15),
(8, 4, 10, NOW(), NOW(), 10),
(8, 7, 12, NOW(), NOW(), 12),
(9, 1, 5, NOW(), NOW(), 5),
(9, 2, 7, NOW(), NOW(), 7),
(9, 6, 9, NOW(), NOW(), 9),
(10, 3, 12, NOW(), NOW(), 12),
(10, 5, 8, NOW(), NOW(), 8),
(10, 8, 6, NOW(), NOW(), 6);
